package port

import (
	"context"

	"github.com/joaoprofile/gofi/iam/types"
)

// IDPAuthPort extends the authentication flow for external providers using OAuth2 and OpenID Connect.
// Each social provider implements this interface.
// Flow: AuthorizationURL redirects the user to the IDP, HandleCallback processes the return,
// then SelectTenant reuses the same logic as the local flow.
type IDPAuthPort interface {
	// AuthorizationURL returns the IDP authorization URL with state and PKCE (S256).
	// The state and code_verifier must be stored in a temporary HttpOnly cookie.
	AuthorizationURL(ctx context.Context, input IDPAuthInput) (*IDPAuthURL, error)

	// HandleCallback processes the IDP callback: validates state, exchanges the code for tokens,
	// fetches the user profile, and returns the normalized IDPUser.
	HandleCallback(ctx context.Context, input IDPCallbackInput) (*IDPCallbackResult, error)

	// ProviderName returns the identifier name of the provider such as "google" or "github".
	ProviderName() string
}

// IDPAuthInput holds the parameters for initiating an OAuth2/OIDC flow.
type IDPAuthInput struct {
	RedirectURI string
	Scopes      []string // extra scopes beyond the minimum set (openid, email, profile)
	State       string   // generated by core, stored in an HttpOnly cookie
	Nonce       string   // for OIDC
}

// IDPAuthURL contains the authorization URL and security values to be stored by the caller.
type IDPAuthURL struct {
	URL           string
	State         string
	CodeVerifier  string // PKCE — store in an HttpOnly cookie
	CodeChallenge string
}

// IDPCallbackInput holds the parameters received in the IDP callback.
type IDPCallbackInput struct {
	Code          string
	State         string
	ExpectedState string // validated against the state stored in the cookie
	CodeVerifier  string // PKCE — retrieved from the cookie
	RedirectURI   string
}

// IDPCallbackResult is the result of processing the callback.
type IDPCallbackResult struct {
	IDPUser   types.IDPUser
	Tenants   []types.TenantAccess // tenants available for the user
	IsNewUser bool                 // true if the user was created during this login
}
